max_width = 100
hard_tabs = true
indent_style = "Block"
binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
trailing_comma = "Never"
fn_params_layout = "Compressed"
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 30
format_code_in_doc_comments = true
format_strings = true
hex_literal_case = "Lower"
imports_granularity = "Module"
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_lit_width = 50
wrap_comments = true
format_macro_matchers = true