#!/bin/bash
curl -L --proto '=https' --tlsv1.2 -sSf -O https://sourceware.org/pub/valgrind/valgrind-3.23.0.tar.bz2
tar -xf valgrind-3.23.0.tar.bz2
rm valgrind-3.23.0.tar.bz2
cd valgrind-3.23.0
./configure
sudo make install -j $(nproc)
