#!/bin/bash
curl -L --proto '=https' --tlsv1.2 -sSf \
  https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh \
  | bash
cargo binstall -y cargo-valgrind cargo-llvm-cov